

services:
  db:
    image: postgres:16
    container_name: pawmatch-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pawMatch
   
    volumes:
      - pawmatch_db:/var/lib/postgresql/data

  app:
    build: .
    container_name: pawmatch-app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db

volumes:
  pawmatch_db: